### ISSUE TITLE
Rename `CUCUMBER_PRO_URL` to `CUCUMBER_PRO_BASE_URL`

### ISSUE THREAD

**Issue by mattwynne** [cucumber-ltd/cucumber-pro-plugin-jvm#1]
I see there's been a great deal of work done in here to build the URL for the user and minimise the amount of configuration they need to do. Great effort!

I'd still like to keep the option open to allow users to specify the whole URL. We don't need to implement it yet, but if we can rename `CUCUMBER_PRO_URL` to `CUCUMBER_PRO_BASE_URL` that will keep that option open.

**Comment by mattwynne** [comment]
This is done, right?

**Comment by aslakhellesoy** [comment]
Yep, done in 1.1.0
