### ISSUE TITLE
Allow users to use a `known_hosts` file instead of setting `CUCUMBER_PRO_GIT_HOST_KEY`

### ISSUE THREAD

**Issue by tooky** [cucumber-ltd/cucumber-pro-plugin-jvm#10]
If users don't set `CUCUMBER_PRO_GIT_HOST_KEY` the build fails. Can we default to trying known_hosts on the server if the host key isn't set?

**Comment by aslakhellesoy** [comment]
Host keys from `~/.ssh/known_hosts` are added automatically. In case this file doesn't exist, or doesn't have the git server's host key, it can be set via `CUCUMBER_PRO_GIT_HOST_KEY`.

I'll make it optional.
