### ISSUE TITLE
Instructive error message when plugin needs to be added to runner class

### ISSUE THREAD

**Issue by mattwynne** [cucumber-ltd/cucumber-pro-plugin-jvm#24]
A user just tried to set this up on a project, and had the following experience:

>  I’m working with Craig Kaminski to set up Cucumber Pro for our new Healthcare Estimator (HCE) service. I updated the cucumber inner source dependency, and updated the Cuke Runner files but am getting a build error “Couldn't load plugin class: io.cucumber.pro.JsonReporter”.
>  
> Is there another plugin that I am missing?

I'm not 100% sure how things fit together, but is it possible for us to give a more helpful error message here that instructs them to add the extra plugin to their runner?

**Comment by mattwynne** [comment]
#2 is related

**Comment by aslakhellesoy** [comment]
Looks like it wasn’t added to the pom.xml

**Comment by mattwynne** [comment]
Yeah my bad.

**Comment by aslakhellesoy** [comment]
Just to be clear. The plugin needs to be added as a dependency in the `pom.xml` *as well as* added to the `@Cucumber.Options` annotation.

Is there anything we can change in the [installation instructions](https://app.cucumber.pro/projects/cucumber-pro-plugin-jvm/documents/branch/master) to make this more clear?

**Comment by mattwynne** [comment]
I think it's fine, it was user error at their end.
