### ISSUE TITLE
environment variables not backwards compatible in 2.x

### ISSUE THREAD

**Issue by mattwynne** [cucumber-ltd/cucumber-pro-plugin-jvm#27]
I just upgraded to 2.1.0 with a client and we got an error that it was trying to hit `app.cucumber.pro`. We set `CUCUMBERPRO_URL` and it worked again.

The changelog says that the old ones will be supported, but it looks like that's not the case.

Just FYI in case anyone else hits this same problem.

**Comment by aslakhellesoy** [comment]
We’re using semver, so it should be ok to break compatibility when we bump minor.
